### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by messense** [lobbyboy-ssh/lobbyboy#43]
```
INF [20211208-07:44:51.056] thr=140672309044992 lobbyboy.utils:127: user choose 1 for option There are 1 available servers:
INF [20211208-07:44:51.056] thr=140672309044992 lobbyboy.socket_handle:79: user choose server input=1.
DEB [20211208-07:44:51.057] thr=140672309044992 lobbyboy.contrib.provider.ignite:86: get ssh to server command for ignite: ['cd dev_datadir/ignite/2021-12-08-0739 && ignite ssh 2021-12-08-0739']
INF [20211208-07:44:51.057] thr=140672309044992 lobbyboy.socket_handle:103: ssh to server 2021-12-08-0739 127.0.0.1: cd dev_datadir/ignite/2021-12-08-0739 && ignite ssh 2021-12-08-0739
INF [20211208-07:44:51.062] thr=140672309044992 lobbyboy.socket_handle:176: proxy subprocess created, pid=71892
CRI [20211208-07:44:51.987] thr=140672309044992 lobbyboy.socket_handle:254: *** Socket thread error.
Traceback (most recent call last):
  File "/root/code/lobbyboy/lobbyboy/socket_handle.py", line 252, in run
    self.cleanup(t, meta=lb_server, check_destroy=True)
  File "/root/code/lobbyboy/lobbyboy/socket_handle.py", line 194, in cleanup
    self.remove_server_session(t, meta.server_name)
  File "/root/code/lobbyboy/lobbyboy/socket_handle.py", line 223, in remove_server_session
    active_session[server_name] = list(filter(lambda x: x.getpeername() != peer_name, sessions))
  File "/root/code/lobbyboy/lobbyboy/socket_handle.py", line 223, in <lambda>
    active_session[server_name] = list(filter(lambda x: x.getpeername() != peer_name, sessions))
  File "/root/.cache/pypoetry/virtualenvs/lobbyboy-P-fHd6h2-py3.8/lib/python3.8/site-packages/paramiko/transport.py", line 1787, in getpeername
    return gp()
OSError: [Errno 9] Bad file descriptor
```

**Comment by laixintao** [comment]
related: https://github.com/lobbyboy-ssh/lobbyboy/issues/21
